### ISSUE TITLE
As a game developer, I would like to view my balance in bitcoin via an API endpoint

### ISSUE THREAD

**Issue by samsheff** [samsheff/hackatomsk2017-tomsktasktic#1]

**Comment by aplinxy9plin** [comment]
Доделано!

**Comment by bmarid** [comment]
Решаем проблему api ethereum

**Comment by bmarid** [comment]
Дизайн рисуется, сейчас мобильная разработка в процессе

**Comment by bmarid** [comment]
Сейчас делаем лицевую сторону карт

**Comment by bmarid** [comment]
Запустили жизнь)

**Comment by bmarid** [comment]
logo_noname_etc

**Comment by bmarid** [comment]
в процессе всего и всея

**Comment by bmarid** [comment]
![ltjfdq54uyg](https://user-images.githubusercontent.com/12098430/32979429-b4f63078-cc87-11e7-8bf5-c92257f2004f.jpg)
Дизайн

**Comment by bmarid** [comment]
теперь у нас есть лого) #
![q7gbxrxp_7e](https://user-images.githubusercontent.com/12098430/32979618-3d2f9580-cc8b-11e7-8e52-bc1a246f345c.jpg)

**Comment by bmarid** [comment]
Распечатали наклеечки)

**Comment by bmarid** [comment]
![pxyh-zpehvy](https://user-images.githubusercontent.com/12098430/32980258-a20f1c3c-cc95-11e7-8d1e-731160e65150.jpg)
еее)

**Comment by bmarid** [comment]
![2017-11-19 1 02 44](https://user-images.githubusercontent.com/12098430/32983464-93d3217c-ccc7-11e7-82df-7e82b0ad67fe.png)
Lending в процессе
